### ISSUE TITLE
关于在梅林固件上运行的问题

### ISSUE THREAD

**Issue by wanglz111** [Anapopo/FChinaNet.sh#2]
我想把这个shell写入路由器，实现自动拨号。
但是写入以后运行不起 显示#!not found
我也不知道是什么问题，请问能给与一些帮助吗

**Comment by Anapopo** [comment]
执行`bash verify.sh`或者`sh verify.sh`试试。

**Comment by scoltzero** [comment]
能在脚本里直接填写账号和密码么？这样不用每次开机都设置一遍了？

**Comment by Anapopo** [comment]
@scoltzero 直接更改脚本内的第4行的AUTH变量内容为`用户名:密码`就好了，注意是英文冒号。

**Comment by scoltzero** [comment]
curl ( 6 ) :couldnt resolve host www . loocha . com . cn
Lol
curl ( 6 ) :Couldnt resolve host wifi.loocha.cn
ocs
curl ( 6 ) :Couldnt resolve host test.f-young.cn
ias
/tmp/Verify . sh : line 39 : hostname : not found
这是我用的华硕ac66u刷的梅林在，用putty在tmp文件夹里运行verify.sh的结果。

**Comment by Anapopo** [comment]
一是没连上校园网，二是不存在`hostname`这个命令哇哦w2。等有空我在openwrt上测试测试😁 @scoltzero

**Comment by Anapopo** [comment]
`Couldnt resolve host`可能是DNS未解析或是未连上网，还有可能是网卡没有配置DHCP自动获取IP
`hostname`这条命令负责显示登录后的设备名称，如果你的路由器内没有这个命令，那你可以手动把[第38行](https://github.com/Anapopo/FChinaNet.sh/blob/master/verify.sh#L38)的$(hostname)改成default

**Comment by scoltzero** [comment]
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
id:
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
code:
wan_ip:  10.15.242.44
bras_ip:  58.213.239.141
verify.sh: line 39: hostname: not found
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
qrcode:
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
确实事外网没连上，不过解决了这个问题后出现了这个问题。说证书有问题。。。

**Comment by scoltzero** [comment]
而且按照你说的把第38行改成$(hostname)改成default后也出现了楼主一开始说的
verify.sh: line 1: #!: not found
凉凉。。。。
不过这个程序再win里面的虚拟机里的Linux里事可以跑的

**Comment by scoltzero** [comment]
@Anapopo

**Comment by scoltzero** [comment]
好像解决了。。。。。。谢谢，那个重置好像还没解决
